modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "quest_api"
version = "${version}"
displayName = "Quest API"
authors = "Fichte"
description = '''
A data-driven quest system: give any entity quests with tasks, requirements, and rewards, defined entirely in JSON.
'''
#logoFile = ""

[[dependencies.quest_api]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quest_api]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quest_api]]
modId = "cloth_config"
type = "required"
versionRange = "[15.0.0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "quest_api.mixins.json"

[[mixins]]
config = "quest_api.neoforge.mixins.json"

[[mixins]]
config = "quest_api.spellengine.mixins.json"
