package com.qeapi.datagen;

import net.minecraft.data.PackOutput;

// Example entity_quest_assignment datagen - each assign(...) writes one
// data/qe_api/entity_quest_assignment/<name>.json, attaching a quest pool (tag) to an entity type
// so it's offered without any code on the entity itself. The pools referenced here are the test
// pools generated by ExampleQuestProvider.
public class ExampleAssignmentProvider extends AssignmentProvider {

    public ExampleAssignmentProvider(PackOutput output) {
        super(output, "qe_api");
    }

    @Override
    protected void addAssignments() {
        // Any villager, 25% of the time, offers the harvest test pool.
        assign("villager_generic", "minecraft:villager")
                .questPool("qe_api:harvest_test")
                .questChance(0.25)
                .add();

        // Only farmer villagers offer the brew pool (villager_data profession matcher).
        assign("villager_farmer", "minecraft:villager")
                .questPool("qe_api:brew_master")
                .villagerProfession("farmer")
                .add();

        // Desert-biome librarian villagers get one of two pools at random, and chunk_restriction
        // keeps only one such villager per 2 chunks holding it.
        assign("villager_desert_librarian", "minecraft:villager")
                .questPool("qe_api:find_mineshaft_map", "qe_api:angler")
                .villager("desert", "librarian")
                .questChance(0.5)
                .chunkRestrictionRadius(2)
                .add();
    }
}
